services:
  psql:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${PG_DB_DATABASE}
      POSTGRES_USER: ${PG_DB_USERNAME}
      POSTGRES_PASSWORD: ${PG_DB_PASSWORD}
    ports:
      - "${PG_DB_PORT}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data

volumes:
  psql_volume:
